[package]
name = "poly_scheduling"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yml = "0.0.12"
serde_json = "1.0"
clingo = { version = "0.8.0", features = ["static-linking"] }
itertools = "0.14.0"